import type { Metadata } from "next";
import { Figtree, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./qui-colors.css";
import { Header } from "@/components/header";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${geistMono.variable} antialiased fixed top-0 left-0 w-screen h-screen bg-muted`}
      >
        <Header />
        <div className="h-[calc(100vh-50px)] max-h-[calc(100vh-50px)] overflow-y-auto">{children}</div>
      </body>
    </html>
  );
}
